# autogenerated by txs
#include:etoolbox
#include:ifluatex
#include:ifxetex
#include:pgfopts
\checkfont{arg1}#S
\iffontsavailable{arg1}{arg2}{arg3}#S
\insertframetitle#S
\insertsectionhead#S
\insertsubsectionhead#S
\insertsubtitle#S
\inserttitle#S
\thefontsnotfound
