# autogenerated by txs
\ProvidesClassRCS#S
\ProvidesFileRCS#S
\ProvidesFile{arg1}#S
\ProvidesPackageRCS#S
\ProvidesPackage{arg1}#S
\next#S
\pgfrcsatcode#S
\pgfrcsloaded#S
\pgfretval#S
\pgfrevision#S
\pgfrevisiondate#S
\pgfrevisiondatetime#S
\pgftypesetversion#S
\pgfversion#S
\pgfversiondate#S
\pgfversiondatetime#S
