# autogenerated by txs
#include:infwarerr
#include:ltxcmds
\MessageBreak#S
\check{arg1}#S
\csname#S
\csname{arg1}#S
\empty#S
\expandafter#S
\next#S
\space#S
\thepage#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
